language: java
sudo: required
jdk: openjdk8
os:
  - linux
dist: xenial
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.local"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
env:
  global:
    - secure: PbKZm9YhyNCeXc6BjWU/X4WNCVDRQGEg7+VaMzAu0FVAwnUO280NxwfSLhGeYnom3ptOr0VdStX6xNbz5tRNQtDL8nfKtfUxDZHR9frPTp7Kqx+cEr3q26ScWpiF/MKzi9++JrPyi/PRiAUtuD4AGwd9sD7N3jcqCIjbAVb8rHMQVifPtLJ2Ms3OV31l6UDnYq1OLipcVRSrKs1vsCe1Km/q2d+m8r/FcLNDHm8YfQQK8dDygB4sQ8WRBcdgaFQdLH8hhB/l4yxWxpLCkssIAueclfV3X58vht2wVJ1sdFpzUUDBGJq0Nc1mueMKNVbSqWyqfmxlOwaUuPBFlj/gYSwFmolW41edDhaVsdvx8dGnJ0ouSSahzetAYJYfvC5u3A3+48zG09InNA8nQD4UEAysbO2DI6W18wzHMifEDViHg58t1PQHIq2IDFi0ZHEi5vZEsjpaY0uI2R9rsmjoiBTXt0My0kAaQkkIwiWw/8dLosMiAR9FSf4Z1vmahCVYNUKYpoBlyU4/4GdMASCwpD5vePVifF2xh4FZjlc6mkoYsbikbmXNzfAkam6p3G1uE4t2c3JO9seRaZiTVqugp4sQ4AgAuu5mgi8wSV9I115ycgGiG6flZwS49GXCWqHqLstUmVxN/+ADKkthCM4Hoc4yZ0PnM6eT+3rmYLdVK8E=
    - secure: TA610OmHSuWRWEgQ9Tm/zY/io/aMICRNkI4CtKttJpV19lG4IwldgGQwhVwsQfPiBSi7/OzETLpl3Gj3qmsq07gMPuklLX3uZfHr4r7nZakr3lrofAieRM1591Fn17yshhjBi4bbNnJH5PMeKy061cONRj4yrAFBYdhtyuq2crsCNk6mFIY8ofS+DDj1dWZe8URE3HWahW9NpHQODBze9J3Cmb/plQtdhylX9ZomDCYtHMeR2hJzQDpNSdGWkwWcjMFBHUON6XelJeRO19MdhZcymz6ybjmJxGsCLFIfL86qKx38C5dxtyt3y7Psh+Yw7nWOWRlbBm7RhlaHm4W8yvurmOZzi4hlWJDP3tljZV6zMeCHSv/UrtBenE33e2JbPX+8/4OocQL0Xg3PtXiy6xlk5DnvhMbXNBOc0V64h8UpOvLh7E0frHobBbBJMr3UHrVKXsfpg7mAhDkS6+TqAyyIGlYR1ds1UrPN5s9lpCR/7KnIc2Lv4Rx7/lRiG6lZ5NYkIGqq4ThpvpWRqWQkqhz16BksxQt94sxk8SmSpxmUixvQfzU1ds3Dr4e6oiEB+f3glRpVy1bLO/lBqVVfU2LW7ITC+3djImGyoAI6N3WanpQRagwqHDuVmO9zVE4aLwvYFmLMq5ApP+wyu/smu/b3mzQN9DPlkrkmcxeNs4M=
    - secure: lRCVG+mB8jGv3QPVVkWH/3I93Xm39YbB0zEkMJ4SXe7JsX66cuDHFCVMY4Eqnxr4LEJVfiRNlPrL3r5YajzQDDBbnPPL0whoY1uT4Cdyd8oUDblK0EMdKeLsqRpwRLG4Nwp7Z7TwrW3TqOHGyPhYZ8MPyrzK3VtQguWgP6xHTA7B4OsFOCgvvf89Sgn7FfC2syoCcn+3vKFR7V/VyXUbOgJzG7aQUPTs7Pfp2jfM9vHm1rarxLqCKy6zEYy2auusfGZqZ8GO8AhPoDSNTNYjsVx5Pi5sTMEGYwHMGwGEIOU6TtCcs4OkPx3dFsb4OeIwAyE/rMjJH7zSmRda/VcCUR++2zgjSneu5K3SZmcRspDIbJQVWegsYmqwFAKwQ8vwmTut5vCM95L642syhYh38naq129T05b516W/VfA1SusqJJJ1x29wz2aGtz+GP5MPwA9eO6xO+UXDpD4JUd9xAgFyVORddIxjp4mIUgY8gpGwjrAnP+v4SX5+1Uz8i1N8Q/pSdZZBDjkyQ1i97M1/+YFVE2QKEKjnn2s/jD5sb+1jauvC+K51gzr6CJ8REU36qJS9Rz5a9QLop/Fw+Oik9s7Fjta3pV0TqUXmfDSFU0OUVVdaX0O9vGscLLG8y4Ocf0UIUs7pc7dPqlDFDkv9Vpxw7rh9+j8Iu/0Msi/RtyU=
    - secure: BhBmDPUzrHftFmIaUbpIMGq3y1Zg5BD98plZRX/5aZ70RQajHGKziTnvaxSaUBTfQeGQHuSc3zTLTmLhHK/F+z9D8oQgkExmIG9t2Ptz9kWeKlk1SokO3a85eT27iYsotYCemaALNbezwjSJFceESD/OPS3M7KaSoFFzv9qogJnHIYsb21JH+9mD7uzkkbfPk5J8MoDWKfQkr7u4GHc7YiuDTlUzzA0qInuU9HvIYYxRD6DLz2lrZ7px/UN4/SB7FUn0I9MdcVW3nzJP2GPpPipp0pLquVLYDvUEl6w8mOGQxhLIzpNDQncL18u5P0EFanU9P679ADv9ziZSpGNWPepxeORMAi+NqkxDhc/GVaUp69uBqZMbXle7fkGRcUWmTR5OBaC4BoDKYr4paQu/bM0t0BGbxe3ThDl6hyKiOa1kNryuN1LLk/wrMvm9QI6ALXgS9rvkc+LAG6FwCt4o7SFfzYaDQmIaQ0h1YUDMdUHWDu3qWFZfoGJNZtQquRsJCh+KjK9eh4dUY2CYqO4SOTj3PQFRnpReWfQdeeJP1GuPlZld9O1E0ce4dhWgkWAck7zCFMa8zggQrHvwgC9dnzKjgEBExMHm28l51Rf+hApB6DOUYqTNOOfErqOarFl7LIYyzXfDy9zKh5yMVawrIBYFFPE/1lic+IshErCn1v4=
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
before_script:
  - chmod +x gradlew
  - echo "${AWS_ACCESS_KEY_ID}"
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set region ${EB_REGION}
  - $(aws ecr get-login --no-include-email)
script:
  - "./gradlew clean dockerPush"
after_success:
  - bash <(curl -s https://codecov.io/bash)
