language: java
sudo: required
jdk: openjdk8
os:
  - linux
dist: xenial
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.local"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
before_script:
  - chmod +x gradlew
  - "$(aws ecr get-login --no-include-email)"
script:
  - "./gradlew clean dockerPush"
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - secure: b2/tjXRSRPOze5EWyw1v2cfjs7sYL4+3PfokndFYVpUndlwVNfc2QTWohr3GVzGUm5WLQVlGBjsSyduF7hXLATBAxmjfNpCHAd5jnvzidLRqDBEGmCF6bXLqDeUoK8fOutZu3Y8zRsZz9QK3cETaAr1wD3F+aqWeUobXpRqKlKkvkQKtdjq3q59XejBNPfdCk+afd2W+VTJNIEd+0sOllBgjI1cv9E7n/53EDEwkibvoi4f/pfH5GrRaScD4KyeTMX8jLV3oZ/thdtu6DPqPFLxKTejT8wxdQlTz2vcR3dzkBNm9y6a+cwsIfQHSmLAMny4KoB0Ler4xmzdCsxtFQd920F2d5bLG6tRuSOvwcXovIv4Gai02PqTLPhSZA6IHgxaue9OmVdtLmYKUFaz6QmJebxlV+KCG71+wgRWbaCgJEydmXKzIon0IvcuGgjsxMiwc0jM9ohjM7XzcPU94JJAby1jx4AMDMK6yV7bc4/WhBsGvrEzyCarFISRHczQESzr697LItdwawpYRxI6sHxAT6ueTTP3igKTQwZncwO25EAezEXAa0LBrdNpbMIOlUXbBYmKwDAcUtsf0jXPlMEPvrjXy/7SVmWoGsMq/SsdBMrYNiZvFnjtlXZuGVbrb4oKcDBmAayu1lHZQYdqd6CPZEzopSax6HtlRIMo9VY0=
    - secure: iptIZbDjxLZci7Vq8/Dxi+w8tfRIPMRdNWMnuaxxtPocb23wSrEf0BieI4qVX2FcY1/Ec0IY24VhxT2Nez3HGM9BKNfC8zA0eLnleZyGSz65aFcTyvYwRUH9u8CcYD+llb5dGR3MgWkIWC81foN8jdHlxMaOnPuQRqfR5Bf8VxGr/0CfUOgntw1D3Kjdvui8lwDjT6SXBbQTYNrxafReU+zFm8iRgxugZKPLq9Y0nwSisYHxT7jJKwKPmJRoZBB9ut3DI9N+hkKDwN/DmTo8kBpnKR6rf6VzZ5TfcazK5IB25x8QhLg7ZBD2RmBgmx4+n4ngbMmFsWbJrCw8t8wPx2DxPiQdHMilyLDyY2m+o1MbCexLj+D7tURUhDq3ota3VEtrq9ir85pRZ9J7C0/mLZiDo67b4vqjIMogfPsI1FWxjyrwa6QVhHQi7wQOISMgWCJiHRf5QIlnp9qiK7VvykSm7Odu4AO9dFsvbOEmqA31yVDNYVqkg8hIHmODU9FvL4OTLvg9hO8zGoLGjrvhhaJGZrhuEARJsfRYO5j3ajLI3k4lBv5UyaainIEgTlogCwgzJJXlPYQHJUi3dtBxRh2yimL9jGla7Mz67/fkvEFEEU7TLxgvLWf5JZ8i4uaDF9Ghp7zDo48zWK8/2Yit2MSODXvVm/Z76LAZGbxesCU=
    - secure: e3RuRMszLzTgibnpLYTzaHZqxzicVUO7KH3xYuxpNVK80IgXDwwgjnzqAspjKXyw03ZWS5S93BVjldEeE1U46oASnMk0exCJkVUvZaknsWaizreY7bdtRNKZh+gdlq3b1ylFOer9nY3+NFCo5CmhgqCMSMG1VSE63rothttdnYMjqwbJRJ9Nvr1ae6dqJe+7zu6o8d9dWUoAXGmxtGWyeFsTFvT4j5G7pcDNJhcQEIMUwGRbmk0L+/F+mo/lwcz90MR50reiR/7nQzcixBgjFQnhp96Kjm9Qo0kA/fAmG75ETUc9wzeJZFLKsbjXyl8NE29jaNgPTZ7SMzTZpzDx8o1RgpcG3rA+GGOPesuwSdmy5WIRMh6ks++rNGluv4bm5+1YuKOmnKvHwqa5+ID5lcMYnWg/SPhhyCLNcz37+0G8NWZqich7yYDzfRCPG2EEY42GQpq/G8LKMRQ2/XfIecSujDpmXa1IdiR+diUgQldV30TSgPSOsc1Rv8uGY57RviZpmdv75qj9UmY9pG91+m0dV4/G/gWdQATyN0CNZ/lHinMBG/UpWWUlbM0KHEvStbnxXnzyO/a4uEqhRmt0dXYUhNbkXK1xtQNAp3OdrealCwGUJs2gm8QpjhgvfGxOvats1gxA2/26zgBdm7JFK6vYMClQDCjubK6yAQ47wd0=
    - secure: I6svplQdZvHzb4nvwHalFwrAotBYwxrC7CzYX9zmA1kl3t1eXzVl+1fAGs7cKvPp3DleiZGWDbYzcOYpxx7GifZppio2f3JQZIx9DfzT8vrkILVDbr+JL77Ymsre4bAdjl0WJhSdRIn2wLA3MjWOegUjIHvkQ6BPf+/EdQLbi4CmCKSn0XgS2YNsMRVqk6PfJEyjuQM63gzDW7XQiSVjFPsvbaUE0IIrg8s/BURkmkTbl0Yq/1JHK1kIoXkqnUr4YupoO+92u4t7v+bz+VL6d1tHSPyztpjLT156v5r6wBXU2gcUuISey7TrVM37PVUV+IARvaNZY/xdxkR7S6ee2pvl48UhXj4a5pyJC5gAcJRpX3zhhasIi7KIY2/HyQQc+v1HiZyq79dYjJ6N9TvsciZXlyT2cBAgN/N2zbYRlP9cCvU4pyhQZ92PdstM/uZsmzH6WJpjqCo9cNMEH8+eVCvO60clgm/Ie+kZ6yzknsC/Wv7TQKUrO2q+yJVczOv2TM8addckss3O96kAoHOsvlxDh8v+W3SCI94H93hqXy4mbpIm+/3DP9/1dB2v9ZIaC8a6H2nsuI5Nvvzhu4IXjg8ZacD7T4l6plX1DUbMU5u0XCCp8T90n1Icr4VTz/28aiznyzWzBVYMbN+h5L5VnG3Fxg+L+l/9gmrmnBAZa3w=
