language: java
sudo: required
jdk: openjdk8
os:
  - linux
dist: xenial
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.local"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
before_script:
  - chmod +x gradlew
  - "$(aws ecr get-login --no-include-email)"
script:
  - "./gradlew clean dockerPush"
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - secure: M6mfhjEIBQxzoUC5QKvF7F7EpszhdzldPMAMq+MfmIZNSkwYz8OH4ttSpnQILzfVspRY85T4xmiZ/4N58ggRCG9UKKCHi4TIH9iBOgItYHaHAYBjQUukVrAh6XjTl7W1LAzyn+WgQgT+zrYCIYtMefmUauiErzEy7W320kFQjehCRn0KwwWWNI4FTKMV6Vx2JP2v6QqWMi8cqrgadjKyZV5E8hDSj4ESVltToUx1/Vlme0Y/jN53TFoRf30Id3c+BUkxs/B0VhxCc9xKc7ed+VLwnKI7okh/iCXle7QDAc5LBmAZq7HviqnQ5OzLAKkVZOroo9XiIIS9Zb3TvpSvfST1P0ZShC98ly9wOpQ/EbFEyQCUK5XG0mC56ot5RfbWVkS7NQNaTPiGOxSh+MPxzaClbL/UzwoV5CbC6NDv3BQTNT6MUoxRoBBRrwXT/E1vrcGnAL2ZhBtptPC5JolBFqjLolpZfHE+cfh1gEtmj4dL7gxjk4v75Psa8t+6yaB6kZkIm1oJOKLlW62dsbL5G4pjYnfHVMKhc6lOAtb3xTcAb4lNUrQFTLfVdNcjHseMJ2H2fNGxmVzSP+AYICd7q5VdQB1WvmLHPvOuRaWLKCXA34MFVyengssbzHAr28u5zLHmPkskDtlbPTCMbqqbvFFo6cSkL827IPWAmE1T7G4=
    - secure: pNOnfduKBdg+F1livXQPYzoOGQp5NGmwkDA9udtyEVbQr+RbT3p/55FGRwmZ+mmkP3vHuxx2g4E8GkcgmZYqMlgBrKRFCV0DmrPPhwn61vC7SFEkI6NQs/93rGnd8v+A3pMQlm6qWpMVSkkm6nEvE0INOxVA2MMZaGWcg8zsaEOrcO3gjdofiyyrDCqC9Gy5MRYp7UZx9m+8EnjnbULNv1gD0TSlxoz5+0p9HrbLwum4XkoKwdVu/bQz+lilSotUT54horgiXlUOTN790uI03VrY2leA+4o3nvxgBbPX/khbPIQUg67j9q/BwwfB08lTgDBr8N6Lc8CV4mgtSiCS5cYMd+TsTsTELGTug0H8NzLcWf5+/ulQlfTIFnKiTbT2tG+rrjPmR0jsGpYMCWhq8Z8AKMJhi8X9MVotfDik0dXtB+P77M/yDm2+tFT+/7P7DwJEmnjvoGYwVF7xBwL0YqXS5zr5I0Wc8jTyrPELTsGJvtCGJmld4vrfYz9NBlPEwV8wKBUG6f6nM1Ywm1MhroWdODQK/5aFsLfY2do9iA16KUprd7wn01nw6KnXIN4mNSIYPCzdmYvPFhEx1A3obUblmoXp+4uOnw3VlXy8paQtsTpIVmdRLJhV09HWEktZ5cGuGVzAmoUMMmDumAX3OZYjCaT1sP9omBafV1Tkxl0=
    - secure: rFxLYVEpnvPDR2C1Arq9X1owKgs39wjSh07PbK3p5QwW8ZARPB19YsusXEXOmDXMtMcX90chRp4Q9/CmiNmm+qMFGjLvDoVyqZ6qb2hTh7URUQG9AmRT63Rp+TXX5kGJDkEmJhdUu6wYmzEwF05tVDIti80Ruk9E+4XK6NKTXPc4crtjzx5NYl4Eim68fASUtEK1ban6g5rE/pJTbM/1pZRPCrgcN/5dXKOO8IVDbT9oYRTazCGt/Ga5ULrSI62+fm0BvGUZCsbvjDtoSqWNrIqX+/psUOK07nnzNB9N5+WvkENNYEQK8dTy5WIticSLUQTN28+/shcsDwZ8tM38HvtDbUzcNYNNBKCpXG4iLzneVD39Cd7OoAP6REGizNvRiOAPX4gS3+yn7DqbKsEXVCyV7RF/+iupOCOm+8Q98uN5EanpiEfWnTxXv+RYpyrv4GJAC2Xvp8xOFnh+gLFlEuSmD5RG+1DzY1qA2cI1VVnjFsmyxFGfHV3cfJCKODVhKCoca5rJPxuVQviOWjUVmvCz60UpyCj2gtYycK4Q1tBTCz25vXHHeWhlH6GnKE+qa5gh+UT1gX2cjQkSSx9KIpS+lfNucydEnqDpvkUUawaTVkE9ClJsHiFqeZHmgZfWU12FsCBUvRAz8dUt8a4MSYhxFWaNha+Jrlfb0IoMjr4=
    - secure: GGp1xsCj5E9OuVcbZyCVc4vLuz00oKiB6esD+mSGheEFntYyZNIdjoB+Dl9fNe5+crwCC/h6Tc2RVcJhrwlaC72TV5t7tsn1eGMwvwSrk5hz42eTUVO58FgX6NCugOdqMKv48Is7GXXI8UsnHgy/XynL35hGNNzukv5lAAfB/mBQEIr1MyCxvYAvT6geeR7Nz8DxnssIhEPnDIjSofKNC5Ff5Ssg53eVoqeMizcYukTJa9XcdvPxzzry5HevCAPZMMZWrJRyKn80b+cyxS4O2gZ9qFK55vt2kbT2qg5+RgbxrEzNWPVsCW+tsoi7Hn7h+M+71dE2WST+8ri57Yh+p86gb4u7yen2xVvQZfmDYw4YxoTjnrpLvMn/SRH8KjduBqFpBVM8NikS50KTTKGhJQ1EvsB8oGMvdS2TDhC7oTih04f7wL7drz5CVNb/iXzlmo8evKgYoj6rJWMa6vOvES3M5n4mmpTFw0LYGFIE0dbYCKq1p8yAXxmvHSNJIkCh/sTsr+05T5JDxXqbruZ7yTPFWjJh/gCc1hLwjiUD8hpp3RAW3EidJh6YHwW3AKhFeKO1d2vLskXtRolhuElVNyjXbb+mOM20DsPhfSuI3tkgFq7kgYSYPuyN8Vl5Xq/xCLFtpJ43Wd+xSBFMjotajsLCPRRouA2idOc9PiLFV90=
